# https://www.home-assistant.io/integrations/default_config/
default_config:

scene: !include scenes.yaml

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.stateful_scenes: debug
    components.mqtt: error

virtual:
